services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  dashboard:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mysql:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mqtt:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  minio:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  scoreboard-simulator:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
