'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4001';
export default function SetupPage() {
  const router = useRouter(); const [step,setStep]=useState(1); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({firstName:'',lastName:'',email:'',username:'',password:'',confirmPassword:'',organizationName:'',defaultSport:'Hockey',timezone:'America/Chicago',serverName:'SportsOS'});
  const update=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  async function finish(){ setError(''); if(form.password!==form.confirmPassword){setError('Passwords do not match.');return;} setBusy(true); const r=await fetch(`${API}/setup/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await r.json(); setBusy(false); if(!r.ok){setError(data.error??'Setup failed');return;} router.push('/login'); }
  return <main className="center"><div className="wizard"><div className="eyebrow">FIRST-RUN SETUP · STEP {step} OF 4</div>{step===1&&<><h1>Welcome to SportsOS</h1><p>Configure your administrator and organization. This usually takes about two minutes.</p><button onClick={()=>setStep(2)}>Begin setup</button></>}{step===2&&<><h1>Create administrator</h1><div className="grid2"><input placeholder="First name" value={form.firstName} onChange={e=>update('firstName',e.target.value)}/><input placeholder="Last name" value={form.lastName} onChange={e=>update('lastName',e.target.value)}/><input placeholder="Email" value={form.email} onChange={e=>update('email',e.target.value)}/><input placeholder="Username" value={form.username} onChange={e=>update('username',e.target.value)}/><input type="password" placeholder="Password (10+ characters)" value={form.password} onChange={e=>update('password',e.target.value)}/><input type="password" placeholder="Confirm password" value={form.confirmPassword} onChange={e=>update('confirmPassword',e.target.value)}/></div><div className="actions"><button className="secondary" onClick={()=>setStep(1)}>Back</button><button onClick={()=>setStep(3)}>Continue</button></div></>}{step===3&&<><h1>Organization</h1><div className="stack"><input placeholder="Organization name" value={form.organizationName} onChange={e=>update('organizationName',e.target.value)}/><input placeholder="Default sport" value={form.defaultSport} onChange={e=>update('defaultSport',e.target.value)}/><input placeholder="Timezone" value={form.timezone} onChange={e=>update('timezone',e.target.value)}/><input placeholder="Server name" value={form.serverName} onChange={e=>update('serverName',e.target.value)}/></div><div className="actions"><button className="secondary" onClick={()=>setStep(2)}>Back</button><button onClick={()=>setStep(4)}>Review</button></div></>}{step===4&&<><h1>Review setup</h1><div className="review"><b>Administrator</b><span>{form.firstName} {form.lastName} · {form.username}</span><b>Organization</b><span>{form.organizationName}</span><b>Sport / timezone</b><span>{form.defaultSport} · {form.timezone}</span><b>Server</b><span>{form.serverName}</span></div>{error&&<p className="error">{error}</p>}<div className="actions"><button className="secondary" onClick={()=>setStep(3)}>Back</button><button disabled={busy} onClick={finish}>{busy?'Creating…':'Create SportsOS'}</button></div></>}</div></main>;
}
