'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import { AuthGate } from '../../components/AuthGate'; import { AppShell } from '../../components/AppShell'; import { API, api, uploadLogo } from '../../lib/api';
type Org={id:number;name:string}; type Team={id:number;organizationId:number;organizationName:string;name:string;nickname:string|null;sport:string;division:string|null;season:string|null;homeArena:string|null;primaryColor:string;secondaryColor:string;logoAssetId:number|null;logoUrl:string|null;active:boolean};
type Form={organizationId:number;name:string;nickname:string; sport:string;division:string;season:string;homeArena:string;primaryColor:string;secondaryColor:string;logoAssetId:number|null;active:boolean};
const blank:Form={organizationId:0,name:'',nickname:'',sport:'Hockey',division:'',season:'2026-27',homeArena:'',primaryColor:'#ef4444',secondaryColor:'#0f172a',logoAssetId:null,active:true};
export default function TeamsPage(){const[orgs,setOrgs]=useState<Org[]>([]);const[items,setItems]=useState<Team[]>([]);const[form,setForm]=useState<Form>(blank);const[editing,setEditing]=useState<number|null>(null);const[search,setSearch]=useState('');const[orgFilter,setOrgFilter]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[file,setFile]=useState<File|null>(null);
const load=useCallback(async()=>{try{const[o,t]=await Promise.all([api<{organizations:Org[]}>('/organizations'),api<{teams:Team[]}>('/teams')]);setOrgs(o.organizations);setItems(t.teams);setForm(f=>f.organizationId?f:{...f,organizationId:o.organizations[0]?.id??0});}catch(e){setError(e instanceof Error?e.message:'Load failed');}},[]);
useEffect(()=>{load();const socket=io(API);['team:created','team:updated','team:deleted','logo:uploaded'].forEach(e=>socket.on(e,load));return()=>{socket.disconnect();};},[load]);
const filtered=useMemo(()=>items.filter(x=>(!orgFilter||x.organizationId===Number(orgFilter))&&`${x.name} ${x.nickname??''} ${x.division??''}`.toLowerCase().includes(search.toLowerCase())),[items,orgFilter,search]);
function edit(x:Team){setEditing(x.id);setForm({organizationId:x.organizationId,name:x.name,nickname:x.nickname??'',sport:x.sport,division:x.division??'',season:x.season??'',homeArena:x.homeArena??'',primaryColor:x.primaryColor,secondaryColor:x.secondaryColor,logoAssetId:x.logoAssetId,active:x.active});window.scrollTo({top:0,behavior:'smooth'});}function reset(){setEditing(null);setFile(null);setError('');setForm({...blank,organizationId:orgs[0]?.id??0});}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let logoAssetId=form.logoAssetId;if(file)logoAssetId=(await uploadLogo(file,form.organizationId)).id;await api(editing?`/teams/${editing}`:'/teams',{method:editing?'PUT':'POST',body:JSON.stringify({...form,nickname:form.nickname||null,division:form.division||null,season:form.season||null,homeArena:form.homeArena||null,logoAssetId})});reset();await load();}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
async function remove(id:number){if(!confirm('Delete this team?'))return;try{await api(`/teams/${id}`,{method:'DELETE'});await load();}catch(e){setError(e instanceof Error?e.message:'Delete failed');}}
return <AuthGate><AppShell><div className="pageHead"><div><h1>Teams</h1><p className="muted">Create and organize teams for future games, rosters, and scoreboards.</p></div><div className="filters"><select value={orgFilter} onChange={e=>setOrgFilter(e.target.value)}><option value="">All organizations</option>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><input className="search" placeholder="Search teams" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
<section className="panel"><h2>{editing?'Edit team':'Add team'}</h2>{!orgs.length?<p>Create an organization first.</p>:<form className="formGrid" onSubmit={save}><label>Organization<select required value={form.organizationId} onChange={e=>setForm({...form,organizationId:Number(e.target.value)})}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Team name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nickname<input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>Sport<input value={form.sport} onChange={e=>setForm({...form,sport:e.target.value})}/></label><label>Division<input value={form.division} onChange={e=>setForm({...form,division:e.target.value})}/></label><label>Season<input value={form.season} onChange={e=>setForm({...form,season:e.target.value})}/></label><label>Home arena<input value={form.homeArena} onChange={e=>setForm({...form,homeArena:e.target.value})}/></label><label>Logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Primary color<input type="color" value={form.primaryColor} onChange={e=>setForm({...form,primaryColor:e.target.value})}/></label><label>Secondary color<input type="color" value={form.secondaryColor} onChange={e=>setForm({...form,secondaryColor:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><div className="formActions"><button disabled={busy}>{busy?'Saving…':editing?'Save changes':'Create team'}</button>{editing&&<button type="button" className="secondary" onClick={reset}>Cancel</button>}</div></form>}{error&&<p className="error">{error}</p>}</section>
<div className="entityGrid">{filtered.map(x=><article className="entityCard" key={x.id}><div className="entityTop">{x.logoUrl?<img className="logo" src={x.logoUrl} alt=""/>:<div className="logo fallback" style={{background:x.primaryColor}}>{(x.nickname||x.name).slice(0,2).toUpperCase()}</div>}<div><h3>{x.name}</h3><p>{x.organizationName}</p></div></div><p>{[x.division,x.season,x.homeArena].filter(Boolean).join(' · ')||'No team details yet'}</p><div className="swatches"><span style={{background:x.primaryColor}}/><span style={{background:x.secondaryColor}}/></div><div className="entityStats"><b>{x.sport}</b><span className={x.active?'badge':'badge off'}>{x.active?'Active':'Inactive'}</span></div><div className="cardActions"><button className="secondary" onClick={()=>edit(x)}>Edit</button><button className="danger" onClick={()=>remove(x.id)}>Delete</button></div></article>)}</div></AppShell></AuthGate>}
