#!/usr/bin/env bash
# SPORTSOS_M32_7_SCHEDULED_SELF_HEALING
set -euo pipefail

ROOT="/mnt/user/appdata/SportsOS-Next"
cd "$ROOT"

export SPORTSOS_RECOVERY_COOLDOWN_SECONDS="${SPORTSOS_RECOVERY_COOLDOWN_SECONDS:-900}"
export SPORTSOS_RECOVERY_BUDGET_WINDOW_SECONDS="${SPORTSOS_RECOVERY_BUDGET_WINDOW_SECONDS:-3600}"
export SPORTSOS_RECOVERY_MAX_ACTIONS_PER_WINDOW="${SPORTSOS_RECOVERY_MAX_ACTIONS_PER_WINDOW:-2}"
export SPORTSOS_RECOVERY_POST_TIMEOUT_SECONDS="${SPORTSOS_RECOVERY_POST_TIMEOUT_SECONDS:-60}"
SPORTSOS_APPLY_RECOVERY=1 bash scripts/run-production-operations.sh recovery
