import { ROLES, type Role } from "./roles.js";

export const PERMISSIONS = {
  ORGANIZATION_READ: "organization.read",
  ORGANIZATION_CREATE: "organization.create",
  ORGANIZATION_UPDATE: "organization.update",
  ORGANIZATION_DELETE: "organization.delete",
  ORGANIZATION_MEMBERS_MANAGE: "organization.members.manage",

  TEAM_READ: "team.read",
  TEAM_CREATE: "team.create",
  TEAM_UPDATE: "team.update",
  TEAM_DELETE: "team.delete",
  TEAM_ROSTER_MANAGE: "team.roster.manage",

  PLAYER_READ: "player.read",
  PLAYER_MANAGE: "player.manage",

  SEASON_READ: "season.read",
  SEASON_MANAGE: "season.manage",

  GAME_READ: "game.read",
  GAME_MANAGE: "game.manage",
  GAME_SCORE: "game.score",

  STREAM_READ: "stream.read",
  STREAM_MANAGE: "stream.manage",

  SCOREBOARD_READ: "scoreboard.read",
  SCOREBOARD_MANAGE: "scoreboard.manage",

  SYSTEM_READ: "system.read",
  SYSTEM_MANAGE: "system.manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS: Readonly<Record<Role, readonly Permission[]>> = {
  [ROLES.SYSTEM_ADMIN]: ALL_PERMISSIONS,

  [ROLES.ORGANIZATION_OWNER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_MANAGE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.TEAM_DELETE,
    PERMISSIONS.TEAM_ROSTER_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_MANAGE,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.SEASON_MANAGE,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.GAME_MANAGE,
    PERMISSIONS.GAME_SCORE,
    PERMISSIONS.STREAM_READ,
    PERMISSIONS.STREAM_MANAGE,
    PERMISSIONS.SCOREBOARD_READ,
    PERMISSIONS.SCOREBOARD_MANAGE,
    PERMISSIONS.SYSTEM_READ,
  ],

  [ROLES.ORGANIZATION_ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MEMBERS_MANAGE,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.TEAM_DELETE,
    PERMISSIONS.TEAM_ROSTER_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_MANAGE,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.SEASON_MANAGE,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.GAME_MANAGE,
    PERMISSIONS.GAME_SCORE,
    PERMISSIONS.STREAM_READ,
    PERMISSIONS.STREAM_MANAGE,
    PERMISSIONS.SCOREBOARD_READ,
    PERMISSIONS.SCOREBOARD_MANAGE,
    PERMISSIONS.SYSTEM_READ,
  ],

  [ROLES.TEAM_ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.TEAM_ROSTER_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_MANAGE,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.GAME_MANAGE,
    PERMISSIONS.GAME_SCORE,
    PERMISSIONS.STREAM_READ,
    PERMISSIONS.STREAM_MANAGE,
    PERMISSIONS.SCOREBOARD_READ,
    PERMISSIONS.SCOREBOARD_MANAGE,
  ],

  [ROLES.COACH]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_ROSTER_MANAGE,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.PLAYER_MANAGE,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.GAME_MANAGE,
  ],

  [ROLES.SCOREKEEPER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.GAME_SCORE,
    PERMISSIONS.SCOREBOARD_READ,
    PERMISSIONS.SCOREBOARD_MANAGE,
  ],

  [ROLES.BROADCASTER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.STREAM_READ,
    PERMISSIONS.STREAM_MANAGE,
    PERMISSIONS.SCOREBOARD_READ,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.TEAM_READ,
    PERMISSIONS.PLAYER_READ,
    PERMISSIONS.SEASON_READ,
    PERMISSIONS.GAME_READ,
    PERMISSIONS.STREAM_READ,
    PERMISSIONS.SCOREBOARD_READ,
  ],
};

export function permissionsForRole(role: Role): readonly Permission[] {
  return ROLE_PERMISSIONS[role];
}

export function roleHasPermission(
  role: Role,
  permission: Permission,
): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
